<script lang="ts">
	import { onMount } from 'svelte';
	import { m } from '$lib/paraglide/messages.js';
	import { FileUp, CloudOff } from '@lucide/svelte';
	// Import Wails backend functions (these are auto-generated by Wails)
	import { OpenFileDialog, ProcessFile } from '../../wailsjs/go/main/App';
	import { OnFileDrop, OnFileDropOff } from '../../wailsjs/runtime/runtime';

	let fileSelected = false;
	let selectedFileName = '';
	let isDragging = false;

	async function handleSelectFile() {
		try {
			// Call Go backend to open native file dialog - returns the file path directly (no memory loading!)
			const filePath = await OpenFileDialog();

			if (filePath) {
				console.log('File selected:', filePath);
				fileSelected = true;
				selectedFileName = filePath.split(/[\\/]/).pop() || filePath;

				// Call your Wails backend function with the file path
				try {
					await ProcessFile(filePath);
					console.log('File processed successfully');
				} catch (err) {
					console.error('Backend processing error:', err);
					// Reset on error
					fileSelected = false;
					selectedFileName = '';
				}
			}
		} catch (err) {
			console.error('File selection error:', err);
		}
	}

	function handleDragEnter() {
		isDragging = true;
	}

	function handleDragLeave(e: DragEvent) {
		// Only set to false if leaving the drop zone entirely
		if (e.currentTarget === e.target) {
			isDragging = false;
		}
	}

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
		isDragging = true;
	}

	onMount(() => {
		// Register drag-and-drop listener from runtime
		OnFileDrop((x: number, y: number, paths: string[]) => {
			isDragging = false; // Reset drag state
			if (paths && paths.length > 0) {
				const p = paths[0];
				fileSelected = true;
				selectedFileName = p.split(/[\\/]/).pop() || p;
				// Fire backend processing
				ProcessFile(p).catch((err) => {
					console.error('Backend processing error (drop):', err);
					fileSelected = false;
					selectedFileName = '';
				});
			}
		}, false); // Set useDropTarget to false since we're handling drag styling ourselves

		// Return cleanup function to remove the listener when component is destroyed
		return () => {
			OnFileDropOff();
		};
	});
</script>

<svelte:head>
	<title>{m['home.home']()}</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<section class="h-full w-full flex flex-col">
	{#if !fileSelected}
		<div class="flex-1 flex items-center justify-center p-4 md:p-6">
			<button
				on:click={handleSelectFile}
				on:dragenter={handleDragEnter}
				on:dragleave={handleDragLeave}
				on:dragover={handleDragOver}
				class="w-full h-full rounded-box border-2 border-dashed transition-all duration-200 flex items-center justify-center shadow-lg cursor-pointer
					{isDragging
					? 'border-primary bg-primary/10 scale-[1.02] shadow-[0_0_0_4px_hsl(var(--p)/0.2)]'
					: 'border-base-content/30 bg-base-200 hover:border-primary hover:bg-base-300'}"
			>
				<div
					class="text-base-content text-lg text-center px-4 sm:px-8 py-4 flex flex-col items-center justify-center h-full"
				>
					<div class="flex-1 flex flex-col items-center justify-center">
						<FileUp class="h-16 w-16 mx-auto mb-4 opacity-50" />
						<p class="font-semibold text-xl">{m['home.click_to_browse']()}</p>
						<p class="text-sm sm:text-sm opacity-75 mt-2">{m['home.any_file_type']()}</p>
					</div>

										<div class="max-w-4xl mx-auto">
						<p class="text-xs opacity-60 mt-4 sm:justify-center">
							<a href="/about" on:click|stopPropagation class="hover:underline">&copy; 2025 TridUI</a> <a
								href="https://go.jm26.net/github"
								target="_blank"
								class="hover:underline"
								rel="noopener noreferrer" on:click|stopPropagation>by Cufiy</a
							>
						</p>
					</div>

					<div class="flex items-center justify-center gap-1.5 text-xs opacity-60 pb-2">
						<CloudOff class="h-4 w-4" />
						<span>{m['home.files_processed_locally']()}</span>
					</div>


				</div>
			</button>
		</div>
	{:else}
		<div class="flex-1 flex justify-center items-center p-4 md:p-6">
			<div class="alert alert-success max-w-2xl w-full">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					class="stroke-current shrink-0 h-6 w-6"
					fill="none"
					viewBox="0 0 24 24"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
					/>
				</svg>
				<div>
					<h3 class="font-bold">Processing: {selectedFileName}</h3>
					<div class="text-sm">Analyzing file with TrID...</div>
				</div>
			</div>
		</div>
	{/if}
</section>
