<script lang="ts">
	import { onMount } from 'svelte';
	import { m } from '$lib/paraglide/messages.js';
	import {
		FileUp,
		CloudOff,
		FileSearch,
		CircleAlert,
		CircleCheck,
		Info,
		Download,
		Search,
		X
	} from '@lucide/svelte';
	// Import Wails backend functions (these are auto-generated by Wails)
	import { OpenFileDialog, ProcessFile, CheckDefinitionsExist } from '../../wailsjs/go/main/App';
	import { OnFileDrop, OnFileDropOff } from '../../wailsjs/runtime/runtime';
	import { main } from '../../wailsjs/go/models';
	import { goto } from '$app/navigation';

	let fileSelected = false;
	let selectedFileName = '';
	let isDragging = false;
	let scanResult: main.TridScanResult | null = null;
	let isScanning = false;
	let definitionsExist = false;
	let showDefinitionsAlert = false;
	let copiedItem: string | null = null;

	async function handleSelectFile() {
		try {
			// Call Go backend to open native file dialog - returns the file path directly (no memory loading!)
			const filePath = await OpenFileDialog();

			if (filePath) {
				await processSelectedFile(filePath);
			}
		} catch (err) {
			console.error('File selection error:', err);
		}
	}

	async function processSelectedFile(filePath: string) {
		console.log('File selected:', filePath);
		
		// Reset state first
		scanResult = null;
		fileSelected = true;
		selectedFileName = filePath.split(/[\\/]/).pop() || filePath;
		
		// Force UI update before starting scan
		await new Promise(resolve => setTimeout(resolve, 0));
		isScanning = true;

		try {
			// Call your Wails backend function with the file path
			const result = await ProcessFile(filePath);
			console.log('Scan result received, matches:', result.totalMatches);
			
			// Update state
			isScanning = false;
			scanResult = result;
			console.log('State updated, isScanning:', isScanning, 'scanResult set:', !!scanResult);
		} catch (err) {
			console.error('Backend processing error:', err);
			// Create an error result
			isScanning = false;
			scanResult = new main.TridScanResult({
				fileName: selectedFileName,
				fileSize: 0,
				matches: [],
				bestMatch: undefined,
				totalMatches: 0,
				error: String(err)
			});
		}
	}

	function handleDragEnter() {
		isDragging = true;
	}

	function handleDragLeave(e: DragEvent) {
		// Only set to false if leaving the drop zone entirely
		if (e.currentTarget === e.target) {
			isDragging = false;
		}
	}

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
		isDragging = true;
	}

	function resetState() {
		fileSelected = false;
		selectedFileName = '';
		scanResult = null;
		isScanning = false;
	}

	function formatFileSize(bytes: number): string {
		if (bytes === 0) return '0 Bytes';
		const k = 1024;
		const sizes = ['Bytes', 'KB', 'MB', 'GB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
	}

	function copyToClipboard(text: string, itemId: string) {
		if (!text) return;
		navigator.clipboard.writeText(text).then(() => {
			copiedItem = itemId;
			setTimeout(() => {
				copiedItem = null;
			}, 2000);
		}).catch((err) => {
			console.error('Could not copy text: ', err);
		});
	}

	function searchOnline(query: string) {
		if (!query) return;
		const url = `https://www.google.com/search?q=${encodeURIComponent(query)}`;
		window.open(url, '_blank');
	}

	onMount(() => {
		// Check if definitions exist
		CheckDefinitionsExist()
			.then((exists) => {
				definitionsExist = exists;
				// Show alert if definitions don't exist
				if (!exists) {
					showDefinitionsAlert = true;
				}
			})
			.catch((err) => {
				console.error('Error checking definitions:', err);
				// Assume definitions don't exist on error
				definitionsExist = false;
				showDefinitionsAlert = true;
			});

		// Register drag-and-drop listener from runtime
		OnFileDrop((x: number, y: number, paths: string[]) => {
			isDragging = false; // Reset drag state
			if (paths && paths.length > 0) {
				processSelectedFile(paths[0]);
			}
		}, false); // Set useDropTarget to false since we're handling drag styling ourselves

		// Return cleanup function to remove the listener when component is destroyed
		return () => {
			OnFileDropOff();
		};
	});

	function goToSettings() {
		goto('/settings');
	}
</script>

<svelte:head>
	<title>{m['home.home']()}</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<section class="h-full w-full flex flex-col">
	{#if !fileSelected}
		<div class="flex-1 flex items-center justify-center p-4 md:p-6">
			<button
				on:click={handleSelectFile}
				on:dragenter={handleDragEnter}
				on:dragleave={handleDragLeave}
				on:dragover={handleDragOver}
				aria-label={m['home.click_to_browse']()}
				class="w-full h-full rounded-box border-2 border-dashed transition-all duration-200 flex items-center justify-center shadow-lg cursor-pointer
					{isDragging
					? 'border-primary bg-primary/10 scale-[1.02] shadow-[0_0_0_4px_hsl(var(--p)/0.2)]'
					: 'border-base-content/30 bg-base-200 hover:border-primary hover:bg-base-300'}"
			>
				<div
					class="text-base-content text-lg text-center px-4 sm:px-8 py-4 flex flex-col items-center justify-center h-full"
				>
					<div class="flex-1 flex flex-col items-center justify-center">
						<FileUp class="h-16 w-16 mx-auto mb-4 opacity-50" />
						<p class="font-semibold text-xl">{m['home.click_to_browse']()}</p>
						<p class="text-sm sm:text-sm opacity-75 mt-2">{m['home.any_file_type']()}</p>
					</div>

					<div class="max-w-4xl mx-auto">
						<p class="text-xs opacity-60 mt-4 sm:justify-center">
							<a href="/about" on:click|stopPropagation class="hover:underline"
								aria-label={m['about.about']()}
								>&copy; 2025 TridUI</a
							>
							<a
								href="https://go.jm26.net/github"
								target="_blank"
								class="hover:underline"
								rel="noopener noreferrer"
								aria-label={m['home.contribute']()}
								on:click|stopPropagation>{m['home.contribute']()}</a
							>
						</p>
					</div>

					<div class="flex items-center justify-center gap-1.5 text-xs opacity-60 pb-2">
						<CloudOff class="h-4 w-4" />
						<span>{m['home.files_processed_locally']()}</span>
					</div>
				</div>
			</button>
		</div>
	{:else}
		<div class="flex-1 flex flex-col p-4 md:p-6 overflow-auto">
			{#if isScanning}
				<div class="flex justify-center items-center flex-1">
					<div class="card bg-base-200 shadow-xl max-w-2xl w-full">
						<div class="card-body items-center text-center gap-6">
							<!-- Animated Scanner Icon -->
							<div class="relative">
								<div class="absolute inset-0 bg-primary/20 rounded-full blur-xl animate-pulse"></div>
								<div class="relative bg-primary/10 p-8 rounded-full">
									<FileSearch class="h-16 w-16 text-primary animate-pulse" />
								</div>
							</div>
							
							<!-- Status Text -->
							<div class="space-y-2">
								<h3 class="text-2xl font-bold">{m['home.scanning']()}</h3>
								<p class="text-sm opacity-70 max-w-md break-all">{selectedFileName}</p>
							</div>
							
							<!-- Loading Animation -->
							<div class="flex gap-2">
								<span class="loading loading-dots loading-lg text-primary"></span>
							</div>
							
							<!-- Progress Message -->
							<div class="text-xs opacity-60">
								{m['home.analyzing_file']()}
							</div>
						</div>
					</div>
				</div>
			{:else if scanResult}
				<div class="max-w-4xl w-full mx-auto space-y-4">
					<!-- Header with file info and reset button -->
					<div class="flex items-center justify-between mt-1 text-wrap">
						<div>
							<h2 class="text-2xl font-bold text-pretty max-w-full wrap-anywhere">{scanResult.fileName}</h2>
							<p class="text-sm opacity-70">{formatFileSize(scanResult.fileSize)}</p>
						</div>
						<button on:click={resetState} class="btn btn-sm btn-ghost" aria-label={m['home.scan_another']()}>{m['home.scan_another']()}</button>
					</div>

					<!-- Error Alert -->
					{#if scanResult.error}
						<div class="alert alert-error">
							<CircleAlert class="h-6 w-6" />
							<div>
								<h3 class="font-bold">{m['home.error']()}</h3>
								<div class="text-sm">{scanResult.error}</div>
							</div>
						</div>
					{/if}

					<!-- Best Match -->
					{#if scanResult.bestMatch}
						<div class="card bg-success/10 border border-success/30">
							<div class="card-body">
									<div class="flex items-start gap-3">
									<CircleCheck class="h-6 w-6 text-success shrink-0 mt-1" />
									<div class="flex-1">
										<h3 class="card-title text-success">{m['home.best_match']()}</h3>
										<div class="mt-2 space-y-2">
											<div>
												<button
													class="tooltip font-semibold cursor-pointer text-left"
													class:tooltip-open={copiedItem === 'best-name'}
													data-tip={copiedItem === 'best-name' ? m['home.copied']() : ''}
													on:click={() => copyToClipboard(scanResult?.bestMatch?.name || '', 'best-name')}
													aria-label={m['home.copy']()}
												>
													<span class="hover:opacity-80">{scanResult.bestMatch.name}</span>
												</button>
												{#if scanResult.bestMatch.extension}
													<button
														class="tooltip badge badge-sm ml-2 cursor-pointer hover:badge-primary"
														class:tooltip-open={copiedItem === 'best-extension'}
														data-tip={copiedItem === 'best-extension' ? m['home.copied']() : ''}
														on:click={() => copyToClipboard(scanResult?.bestMatch?.extension || '', 'best-extension')}
														aria-label={m['home.copy']()}
													>
														.{scanResult.bestMatch.extension}
													</button>
												{/if}
												<!-- search online button -->
												<button
													class="badge badge-sm ml-1 cursor-pointer hover:badge-primary"
													on:click={() => searchOnline(scanResult?.bestMatch?.name  + ' (' + scanResult?.bestMatch?.extension + ')' )}
													aria-label={m['home.search_online']()}
												>
													<Search class="h-4 w-4" />
												</button>
											</div>
											{#if scanResult.bestMatch.description}
												<button class="text-sm cursor-pointer tooltip" class:tooltip-open={copiedItem === 'best-description'}
													data-tip={copiedItem === 'best-description' ? m['home.copied']() : ''}
													on:click={() => copyToClipboard(scanResult?.bestMatch?.description || '', 'best-description')}
													aria-label={m['home.copy']()}
												>
													<span class="hover:opacity-60 opacity-80 inline">{scanResult.bestMatch.description}</span>
												</button>
											{/if}
											<div class="flex items-center gap-4 text-sm">
												<div>
													<span class="opacity-70">{m['home.confidence']()}:</span>
													<span class="font-semibold ml-1 select-text"
														>{scanResult.bestMatch.confidence.toFixed(1)}%</span
													>
												</div>
												{#if scanResult.bestMatch.mimeType}
													<div>
														<span class="opacity-70">MIME:</span>
														<button
															class="tooltip font-mono text-xs ml-1 cursor-pointer"
															class:tooltip-open={copiedItem === 'best-mime'}
															data-tip={copiedItem === 'best-mime' ? m['home.copied']() : ''}
															on:click={() => copyToClipboard(scanResult?.bestMatch?.mimeType || '', 'best-mime')}
															aria-label={m['home.copy']()}
														>
															<span class="hover:opacity-80 inline">{scanResult.bestMatch.mimeType}</span>
														</button>
													</div>
												{/if}
											</div>
											{#if scanResult.bestMatch.remarks}
												<p class="text-xs opacity-60 mt-2">
													<Info class="h-3 w-3 inline mr-1" />{scanResult.bestMatch.remarks}
												</p>
											{/if}
										</div>
									</div>
								</div>
							</div>
						</div>
					{/if}

					<!-- Other Matches -->
					{#if scanResult.matches && scanResult.matches.length > 1}
						<div class="card bg-base-200">
							<div class="card-body">
								<h3 class="card-title text-base">
									{m['home.other_possible_matches']()} ({scanResult.totalMatches - 1})
								</h3>
								<div class="space-y-2 mt-2">
									{#each scanResult.matches.slice(1, 6) as match, index}
										<div class="border-l-2 border-base-300 pl-3 py-1">
											<div class="flex items-center justify-between">
												<div>
													<button
														class="tooltip font-medium cursor-pointer text-left"
														class:tooltip-open={copiedItem === `match-${index}-name`}
														data-tip={copiedItem === `match-${index}-name` ? m['home.copied']() : ''}
														on:click={() => copyToClipboard(match.name, `match-${index}-name`)}
														aria-label={m['home.copy']()}
													>
														<span class="hover:opacity-80">{match.name}</span>
													</button>
													{#if match.extension}
														<button
															class="tooltip badge badge-xs ml-2 cursor-pointer hover:badge-primary"
															class:tooltip-open={copiedItem === `match-${index}-ext`}
															data-tip={copiedItem === `match-${index}-ext` ? m['home.copied']() : ''}
															on:click={() => copyToClipboard(match.extension || '', `match-${index}-ext`)}
															aria-label={m['home.copy']()}
														>
															.{match.extension}
														</button>
													{/if}
													<!-- search online button -->
													<button
														class="badge badge-xs ml-1 cursor-pointer hover:badge-primary"
														on:click={() => searchOnline(match.name + ' (' + match.extension + ')')}
														aria-label={m['home.search_online']()}
													>
														<Search class="h-3 w-3" />
													</button>
												</div>
												<span class="text-sm opacity-70 select-text"
													>{match.confidence.toFixed(1)}%</span
												>
											</div>
											{#if match.description}
												<button class="text-sm cursor-pointer tooltip" class:tooltip-open={copiedItem === 'match-description'}
													data-tip={copiedItem === 'match-description' ? m['home.copied']() : ''}
													on:click={() => copyToClipboard(match?.description || '', 'match-description')}
													aria-label={m['home.copy']()}
												>
													<span class="hover:opacity-60 opacity-80 inline">{match.description}</span>
												</button>											{/if}
										</div>
								{/each}
								{#if scanResult.totalMatches > 6}
									<p class="text-xs opacity-60 text-center pt-2">
										{m['home.more_possible_matches']({ count: scanResult.totalMatches - 6 })}.
									</p>
								{/if}
								</div>
							</div>
						</div>
					{:else if scanResult.totalMatches === 0}
						<div class="card bg-base-200">
							<div class="card-body">
								<div class="flex flex-col items-center text-center gap-4 py-8">
									<div class="relative">
										<div class="absolute inset-0 bg-warning/20 rounded-full blur-xl"></div>
										<div class="relative bg-warning/10 p-6 rounded-full">
											<CircleAlert class="h-12 w-12 text-warning" />
										</div>
									</div>
									<div class="space-y-2">
										<h3 class="text-xl font-bold">{m['home.no_matches_found']()}</h3>
										<p class="text-sm opacity-70 max-w-md">
											{m['home.no_matches_explanation']()}
										</p>
									</div>
									<button on:click={resetState} class="btn btn-sm btn-ghost mt-2" aria-label={m['home.scan_another']()}>
										{m['home.scan_another']()}
									</button>
								</div>
							</div>
						</div>
					{/if}
				</div>
			{/if}
		</div>
	{/if}
</section>

{#if showDefinitionsAlert}
	<div class="alert alert-soft alert-warning mt-4 z-50 shadow-lg fixed bottom-3 md:bottom-6 max-w-md flex items-start gap-4 mr-20 ml-4">
		<CircleAlert class="h-6 w-6 text-warning my-auto" />
		<div class="flex-1">
			<h3 class="font-bold">{m['home.definitions_not_found']()}</h3>
			<div class="text-sm">{m['home.definitions_not_found_explanation']()}</div>
		</div>
		<div class="flex gap-2 my-auto">
			<button class="btn btn-sm btn-warning" on:click={goToSettings} aria-label={m['home.download']()}>
				<Download class="h-4 w-4" />
				{m['home.download']()}
			</button>
		</div>
	</div>
{/if}
