<script lang="ts">
	import { onMount } from 'svelte';
	import { m } from '$lib/paraglide/messages.js';
	import {
		FileUp,
		CloudOff,
		FileSearch,
		AlertCircle,
		CheckCircle2,
		Info,
		Download,
		X
	} from '@lucide/svelte';
	// Import Wails backend functions (these are auto-generated by Wails)
	import { OpenFileDialog, ProcessFile, CheckDefinitionsExist } from '../../wailsjs/go/main/App';
	import { OnFileDrop, OnFileDropOff } from '../../wailsjs/runtime/runtime';
	import { main } from '../../wailsjs/go/models';
	import { goto } from '$app/navigation';

	let fileSelected = false;
	let selectedFileName = '';
	let isDragging = false;
	let scanResult: main.TridScanResult | null = null;
	let isScanning = false;
	let definitionsExist = false;
	let showDefinitionsAlert = false;

	async function handleSelectFile() {
		try {
			// Call Go backend to open native file dialog - returns the file path directly (no memory loading!)
			const filePath = await OpenFileDialog();

			if (filePath) {
				await processSelectedFile(filePath);
			}
		} catch (err) {
			console.error('File selection error:', err);
		}
	}

	async function processSelectedFile(filePath: string) {
		console.log('File selected:', filePath);
		fileSelected = true;
		isScanning = true;
		selectedFileName = filePath.split(/[\\/]/).pop() || filePath;
		scanResult = null;

		try {
			// Call your Wails backend function with the file path
			const result = await ProcessFile(filePath);
			console.log('Scan result:', result);
			scanResult = result;
		} catch (err) {
			console.error('Backend processing error:', err);
			// Create an error result
			scanResult = new main.TridScanResult({
				fileName: selectedFileName,
				fileSize: 0,
				matches: [],
				bestMatch: undefined,
				totalMatches: 0,
				error: String(err)
			});
		} finally {
			isScanning = false;
		}
	}

	function handleDragEnter() {
		isDragging = true;
	}

	function handleDragLeave(e: DragEvent) {
		// Only set to false if leaving the drop zone entirely
		if (e.currentTarget === e.target) {
			isDragging = false;
		}
	}

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
		isDragging = true;
	}

	function resetState() {
		fileSelected = false;
		selectedFileName = '';
		scanResult = null;
		isScanning = false;
	}

	function formatFileSize(bytes: number): string {
		if (bytes === 0) return '0 Bytes';
		const k = 1024;
		const sizes = ['Bytes', 'KB', 'MB', 'GB'];
		const i = Math.floor(Math.log(bytes) / Math.log(k));
		return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
	}

	onMount(() => {
		// Check if definitions exist
		CheckDefinitionsExist()
			.then((exists) => {
				definitionsExist = exists;
				// Show alert if definitions don't exist
				if (!exists) {
					showDefinitionsAlert = true;
				}
			})
			.catch((err) => {
				console.error('Error checking definitions:', err);
				// Assume definitions don't exist on error
				definitionsExist = false;
				showDefinitionsAlert = true;
			});

		// Register drag-and-drop listener from runtime
		OnFileDrop((x: number, y: number, paths: string[]) => {
			isDragging = false; // Reset drag state
			if (paths && paths.length > 0) {
				processSelectedFile(paths[0]);
			}
		}, false); // Set useDropTarget to false since we're handling drag styling ourselves

		// Return cleanup function to remove the listener when component is destroyed
		return () => {
			OnFileDropOff();
		};
	});

	function goToSettings() {
		goto('/settings');
	}
</script>

<svelte:head>
	<title>{m['home.home']()}</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<section class="h-full w-full flex flex-col">
	{#if !fileSelected}
		<div class="flex-1 flex items-center justify-center p-4 md:p-6">
			<button
				on:click={handleSelectFile}
				on:dragenter={handleDragEnter}
				on:dragleave={handleDragLeave}
				on:dragover={handleDragOver}
				class="w-full h-full rounded-box border-2 border-dashed transition-all duration-200 flex items-center justify-center shadow-lg cursor-pointer
					{isDragging
					? 'border-primary bg-primary/10 scale-[1.02] shadow-[0_0_0_4px_hsl(var(--p)/0.2)]'
					: 'border-base-content/30 bg-base-200 hover:border-primary hover:bg-base-300'}"
			>
				<div
					class="text-base-content text-lg text-center px-4 sm:px-8 py-4 flex flex-col items-center justify-center h-full"
				>
					<div class="flex-1 flex flex-col items-center justify-center">
						<FileUp class="h-16 w-16 mx-auto mb-4 opacity-50" />
						<p class="font-semibold text-xl">{m['home.click_to_browse']()}</p>
						<p class="text-sm sm:text-sm opacity-75 mt-2">{m['home.any_file_type']()}</p>
					</div>

					<div class="max-w-4xl mx-auto">
						<p class="text-xs opacity-60 mt-4 sm:justify-center">
							<a href="/about" on:click|stopPropagation class="hover:underline"
								>&copy; 2025 TridUI</a
							>
							<a
								href="https://go.jm26.net/github"
								target="_blank"
								class="hover:underline"
								rel="noopener noreferrer"
								on:click|stopPropagation>by Cufiy</a
							>
						</p>
					</div>

					<div class="flex items-center justify-center gap-1.5 text-xs opacity-60 pb-2">
						<CloudOff class="h-4 w-4" />
						<span>{m['home.files_processed_locally']()}</span>
					</div>
				</div>
			</button>
		</div>
	{:else}
		<div class="flex-1 flex flex-col p-4 md:p-6 overflow-auto">
			{#if isScanning}
				<div class="flex justify-center items-center flex-1">
					<div class="alert alert-info max-w-2xl w-full">
						<FileSearch class="h-6 w-6 animate-pulse" />
						<div>
							<h3 class="font-bold">Scanning: {selectedFileName}</h3>
							<div class="text-sm">Analyzing file with TrID...</div>
						</div>
					</div>
				</div>
			{:else if scanResult}
				<div class="max-w-4xl w-full mx-auto space-y-4">
					<!-- Header with file info and reset button -->
					<div class="flex items-center justify-between">
						<div>
							<h2 class="text-2xl font-bold">{scanResult.fileName}</h2>
							<p class="text-sm opacity-70">{formatFileSize(scanResult.fileSize)}</p>
						</div>
						<button on:click={resetState} class="btn btn-sm btn-ghost">Scan Another</button>
					</div>

					<!-- Error Alert -->
					{#if scanResult.error}
						<div class="alert alert-error">
							<AlertCircle class="h-6 w-6" />
							<div>
								<h3 class="font-bold">Error</h3>
								<div class="text-sm">{scanResult.error}</div>
							</div>
						</div>
					{/if}

					<!-- Best Match -->
					{#if scanResult.bestMatch}
						<div class="card bg-success/10 border border-success/30">
							<div class="card-body">
								<div class="flex items-start gap-3">
									<CheckCircle2 class="h-6 w-6 text-success shrink-0 mt-1" />
									<div class="flex-1">
										<h3 class="card-title text-success">Best Match</h3>
										<div class="mt-2 space-y-2">
											<div>
												<span class="font-semibold">{scanResult.bestMatch.name}</span>
												{#if scanResult.bestMatch.extension}
													<span class="badge badge-sm ml-2"
														>.{scanResult.bestMatch.extension}</span
													>
												{/if}
											</div>
											{#if scanResult.bestMatch.description}
												<p class="text-sm opacity-80">{scanResult.bestMatch.description}</p>
											{/if}
											<div class="flex items-center gap-4 text-sm">
												<div>
													<span class="opacity-70">Confidence:</span>
													<span class="font-semibold ml-1"
														>{scanResult.bestMatch.confidence.toFixed(1)}%</span
													>
												</div>
												{#if scanResult.bestMatch.mimeType}
													<div>
														<span class="opacity-70">MIME:</span>
														<span class="font-mono text-xs ml-1"
															>{scanResult.bestMatch.mimeType}</span
														>
													</div>
												{/if}
											</div>
											{#if scanResult.bestMatch.remarks}
												<p class="text-xs opacity-60 mt-2">
													<Info class="h-3 w-3 inline mr-1" />{scanResult.bestMatch.remarks}
												</p>
											{/if}
										</div>
									</div>
								</div>
							</div>
						</div>
					{/if}

					<!-- Other Matches -->
					{#if scanResult.matches && scanResult.matches.length > 1}
						<div class="card bg-base-200">
							<div class="card-body">
								<h3 class="card-title text-base">
									Other Possible Matches ({scanResult.totalMatches - 1})
								</h3>
								<div class="space-y-2 mt-2">
									{#each scanResult.matches.slice(1, 6) as match}
										<div class="border-l-2 border-base-300 pl-3 py-1">
											<div class="flex items-center justify-between">
												<div>
													<span class="font-medium">{match.name}</span>
													{#if match.extension}
														<span class="badge badge-xs ml-2">.{match.extension}</span>
													{/if}
												</div>
												<span class="text-sm opacity-70"
													>{match.confidence.toFixed(1)}%</span
												>
											</div>
											{#if match.description}
												<p class="text-xs opacity-60 mt-1">{match.description}</p>
											{/if}
										</div>
									{/each}
									{#if scanResult.totalMatches > 6}
										<p class="text-xs opacity-60 text-center pt-2">
											...and {scanResult.totalMatches - 6} more matches
										</p>
									{/if}
								</div>
							</div>
						</div>
					{:else if scanResult.totalMatches === 0}
						<div class="alert alert-warning">
							<AlertCircle class="h-6 w-6" />
							<div>
								<h3 class="font-bold">No Matches Found</h3>
								<div class="text-sm">
									TrID could not identify this file type. It may be a rare or custom format.
								</div>
							</div>
						</div>
					{/if}
				</div>
			{/if}
		</div>
	{/if}
</section>

{#if showDefinitionsAlert}
	<div class="alert alert-soft alert-warning mt-4 z-50 shadow-lg fixed bottom-3 md:bottom-6 max-w-md flex items-start gap-4 mr-20 ml-4">
		<AlertCircle class="h-6 w-6 text-warning my-auto" />
		<div class="flex-1">
			<h3 class="font-bold">Definitions Not Found</h3>
			<div class="text-sm">TrID definitions are required to scan files. Please download them to continue.</div>
		</div>
		<div class="flex gap-2 my-auto">
			<button class="btn btn-sm btn-warning" on:click={goToSettings}>
				<Download class="h-4 w-4" />
				Download
			</button>
		</div>
	</div>
{/if}
