// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDefinitionsExist():Promise<boolean>;

export function CheckForDefsUpdates():Promise<main.TridUpdateInfo>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function GetConfig():Promise<string>;

export function GetDefinitionsPath():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenAppDir():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function ProcessFile(arg1:string,arg2:number):Promise<main.TridScanResult>;

export function UpdateDefinitions():Promise<void>;
