// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTrid() {
  return window['go']['main']['App']['CheckTrid']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenAppDir() {
  return window['go']['main']['App']['OpenAppDir']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ProcessFile(arg1) {
  return window['go']['main']['App']['ProcessFile'](arg1);
}
