// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTrid():Promise<void>;

export function GetConfig():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenAppDir():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function ProcessFile(arg1:string):Promise<void>;
