// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDefinitionsExist() {
	return window['go']['main']['App']['CheckDefinitionsExist']();
}

export function CheckForDefsUpdates() {
	return window['go']['main']['App']['CheckForDefsUpdates']();
}

export function CheckForUpdates() {
	return window['go']['main']['App']['CheckForUpdates']();
}

export function GetConfig() {
	return window['go']['main']['App']['GetConfig']();
}

export function GetDefinitionsPath() {
	return window['go']['main']['App']['GetDefinitionsPath']();
}

export function GetOSName() {
	return window['go']['main']['App']['GetOSName']();
}

export function GetVersion() {
	return window['go']['main']['App']['GetVersion']();
}

export function OpenAppDir() {
	return window['go']['main']['App']['OpenAppDir']();
}

export function OpenFileDialog() {
	return window['go']['main']['App']['OpenFileDialog']();
}

export function ProcessFile(arg1, arg2) {
	return window['go']['main']['App']['ProcessFile'](arg1, arg2);
}

export function UpdateDefinitions() {
	return window['go']['main']['App']['UpdateDefinitions']();
}
