name: "Build macOS App (Universal)"
on:
  workflow_dispatch:
    # This allows manual triggering from the GitHub Actions tab

jobs:
  build-macos-universal:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Clean build directory
        run: |
          rm -rf build/bin/darwin
          mkdir -p build/bin/darwin

      - name: Build Wails application (universal)
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          wails build -platform darwin/universal -clean
          mkdir -p build/bin/darwin
          if [ -d "build/bin/TridUI.app" ]; then
            cp -R build/bin/TridUI.app build/bin/darwin/TridUI.app
          fi

      # Optional: Code signing steps - uncomment when you have certificates
      # - name: Install gon for macOS code signing and notarization
      #   run: |
      #     brew install mitchellh/gon/gon
      # 
      # - name: Import Code-Signing Certificates
      #   uses: Apple-Actions/import-codesign-certs@v1
      #   with:
      #     p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      #     p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      # 
      # - name: Sign macOS binary
      #   run: |
      #     echo "Signing Package"
      #     gon -log-level=info ./build/darwin/gon-sign.json

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Create DMG and ZIP
        run: |
          # Create ZIP of TridUI.app
          cd build/bin/darwin && zip -r TridUI-macOS.zip TridUI.app && cd ../../..
          
          # Use icon from build dir or fall back to repo root
          ICON_PATH="build/appicon.png"
          if [ ! -f "$ICON_PATH" ]; then
            ICON_PATH="icon.png"
          fi
          
          # Create DMG
          create-dmg \
            --volname "TrID UI" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "TridUI.app" 175 190 \
            --hide-extension "TridUI.app" \
            --app-drop-link 425 190 \
            "build/bin/darwin/TridUI-macOS.dmg" \
            "build/bin/darwin/TridUI.app" || echo "DMG creation failed, but ZIP is available"

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: TridUI-macos-universal
          path: build/bin/darwin/*
          retention-days: 7
